language: node_js
node_js:
  - v7
  - v6
notifications:
  email:
    recipients:
      - cas.eliens@gmail.com
    on_success: change
    on_failure: change
install:
  - npm install -g gulp
  - npm install --no-optional
script: npm test
